create table t_cinfo (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    content TEXT,
    keyword varchar(250),
    title varchar(250),
    type varchar(20),
    primary key (id)
);

create table t_dict (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    name varchar(100),
    type varchar(20),
    primary key (id)
);

create table t_disinfectant_instock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    element varchar(60),
    expirydate datetime,
    indate datetime,
    inuser_id int default 0,
    location varchar(60),
    stock_id int default 0,
    vendor varchar(60),
    wrap varchar(60),
    primary key (id)
);
 
create table t_disinfectant_outstock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    cell_id int default 0,
    outdate datetime,
    outuser_id int default 0,
    register_id int default 0,
    stock_id int default 0,
    primary key (id)
);
create table t_disinfectant_resource (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    name varchar(60),
    type varchar(20),
    primary key (id)
);
create table t_disinfectant_stock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    primary key (id)
);
create table t_feed_instock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    element varchar(60),
    expirydate datetime,
    indate datetime,
    inuser_id int default 0,
    location varchar(60),
    stock_id int default 0,
    vendor varchar(60),
    wrap varchar(60),
    primary key (id)
);
create table t_feed_outstock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    cell_id int default 0,
    outdate datetime,
    outuser_id int default 0,
    register_id int default 0,
    stock_id int default 0,
    primary key (id)
);
create table t_feed_resource (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    name varchar(60),
    type varchar(20),
    primary key (id)
);
create table t_feed_stock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    primary key (id)
);
create table t_grow_farm (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    activitydate datetime,
    cell_id int default 0,
    content varchar(255),
    manager varchar(60),
    persons int default 0,
    register_id int default 0,
    scale decimal(10, 2) default 0,
    primary key (id)
);
create table t_grow_harvest (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch int default 0,
    cell_id int default 0,
    method varchar(60),
    operatedate datetime,
    product varchar(100),
    register_id int default 0,
    respmanager varchar(60),
    scale decimal(10, 2) default 0,
    storage varchar(60),
    storemanager varchar(60),
    yield decimal(10, 2) default 0,
    primary key (id)
);
create table t_grow_irrigate (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    area decimal(10,2) default 0,
    cell_id int default 0,
    date datetime,
    manager varchar(60),
    quantum decimal(10,2) default 0,
    register_id int default 0,
    way varchar(30),
    primary key (id)
);
create table t_grow_manure (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    cell_id int default 0,
    isolation decimal(10,2) default 0,
    machinecate integer,
    method integer,
    name_id int default 0,
    reason varchar(100),
    register_id int default 0,
    stock_id int default 0,
    tech varchar(60),
    usedate datetime,
    useperson varchar(60),
    useqty decimal(10,2) default 0,
    primary key (id)
);
create table t_grow_pesticide (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    cell_id int default 0,
    isolation decimal(10,2) default 0,
    machinecate integer,
    method integer,
    name_id int default 0,
    reason varchar(100),
    register_id int default 0,
    stock_id int default 0,
    tech varchar(60),
    usedate datetime,
    useperson varchar(60),
    useqty decimal(10,2) default 0,
    primary key (id)
);
create table t_grow_register (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    cell_id int default 0,
    description varchar(100),
    growstatus int default 0,
    person varchar(36),
    product_id integer,
    qrcode longblob,
    regdate datetime,
    reguser_id int default 0,
    primary key (id)
);
create table t_grow_resource (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    name varchar(60),
    type int default 0,
    primary key (id)
);

create table t_manure_instock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    element varchar(60),
    expirydate datetime,
    indate datetime,
    inuser_id int default 0,
    location varchar(60),
    stock_id int default 0,
    vendor varchar(60),
    wrap varchar(60),
    primary key (id)
);
create table t_manure_outstock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    cell_id int default 0,
    outdate datetime,
    outuser_id int default 0,
    register_id int default 0,
    stock_id int default 0,
    primary key (id)
);
create table t_manure_resource (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    name varchar(60),
    type varchar(20),
    primary key (id)
);
create table t_manure_stock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    primary key (id)
);
create table t_medicine_instock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    element varchar(60),
    expirydate datetime,
    indate datetime,
    inuser_id int default 0,
    location varchar(60),
    stock_id int default 0,
    vendor varchar(60),
    wrap varchar(60),
    primary key (id)
);
create table t_medicine_outstock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    cell_id int default 0,
    outdate datetime,
    outuser_id int default 0,
    register_id int default 0,
    stock_id int default 0,
    primary key (id)
);
create table t_medicine_resource (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    name varchar(60),
    type varchar(20),
    primary key (id)
);
create table t_medicine_stock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    primary key (id)
);
create table t_nurture_farm (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    activitydate datetime,
    cell_id int default 0,
    content varchar(255),
    manager varchar(60),
    persons int default 0,
    register_id int default 0,
    scale decimal(10, 2) default 0,
    primary key (id)
);
create table t_nurture_harvest (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch int default 0,
    cell_id int default 0,
    method varchar(60),
    operatedate datetime,
    product varchar(100),
    register_id int default 0,
    respmanager varchar(60),
    scale decimal(10, 2) default 0,
    storage varchar(60),
    storemanager varchar(60),
    yield decimal(10, 2) default 0,
    primary key (id)
);
create table t_nurture_irrigate (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    area decimal(10,2) default 0,
    cell_id int default 0,
    date datetime,
    manager varchar(60),
    quantum decimal(10,2) default 0,
    register_id int default 0,
    way varchar(30),
    primary key (id)
);
create table t_nurture_manure (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    cell_id int default 0,
    isolation decimal(10,2) default 0,
    machinecate integer,
    method integer,
    name_id int default 0,
    reason varchar(100),
    register_id int default 0,
    stock_id int default 0,
    tech varchar(60),
    usedate datetime,
    useperson varchar(60),
    useqty decimal(10,2) default 0,
    primary key (id)
);
create table t_nurture_pesticide (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    cell_id int default 0,
    isolation decimal(10,2) default 0,
    machinecate integer,
    method integer,
    name_id int default 0,
    reason varchar(100),
    register_id int default 0,
    stock_id int default 0,
    tech varchar(60),
    usedate datetime,
    useperson varchar(60),
    useqty decimal(10,2) default 0,
    primary key (id)
);
create table t_nurture_register (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    cell_id int default 0,
    description varchar(100),
    nurturestatus int default 0,
    person varchar(36),
    product_id integer,
    qrcode longblob,
    regdate datetime,
    reguser_id int default 0,
    primary key (id)
);
create table t_pesticide_instock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    element varchar(60),
    expirydate datetime,
    indate datetime,
    inuser_id int default 0,
    location varchar(60),
    stock_id int default 0,
    vendor varchar(60),
    wrap varchar(60),
    primary key (id)
);
create table t_pesticide_outstock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    cell_id int default 0,
    outdate datetime,
    outuser_id int default 0,
    register_id int default 0,
    stock_id int default 0,
    primary key (id)
);
create table t_pesticide_resource (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    name varchar(60),
    type varchar(20),
    primary key (id)
);
create table t_pesticide_stock (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    batch_id int default 0,
    kind_id int default 0,
    name_id int default 0,
    producer_id int default 0,
    quantity decimal(10,2) default 0,
    spec_id int default 0,
    primary key (id)
);
create table t_production_cell (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    area decimal(10,2) default 0,
    builddate datetime,
    code varchar(255),
    location varchar(255),
    usestatus int default 0,
    primary key (id)
);
 
create table t_user (
    id integer not null auto_increment,
    adate datetime,
    auser_id int default 0,
    cdate datetime,
    comment varchar(255),
    cuser_id int default 0,
    status int default 0,
    udate datetime,
    uuser_id int default 0,
    pass_word varchar(20),
    user_id varchar(20),
    user_name varchar(60),
    primary key (id)
);