CREATE TABLE ASUSER(--User
	ASUSER_USERID 			VARCHAR(36)  		DEFAULT ''	NOT NULL,
	ASUSER_USERNAME   		VARCHAR(60)   		DEFAULT '',
	ASUSER_EMAIL			VARCHAR(80)			DEFAULT '',
	PRIMARY KEY (ASUSER_USERID)
);