INSERT INTO ASUSER (ASUSER_USERID,ASUSER_USERNAME,ASUSER_EMAIL,ASUSER_PWD) VALUES('ADMIN1','Administrator1','someone1@norming.com.cn','admin');
INSERT INTO ASUSER (ASUSER_USERID,ASUSER_USERNAME,ASUSER_EMAIL,ASUSER_PWD) VALUES('ADMIN2','Administrator2','someone2@norming.com.cn','admin');
INSERT INTO ASUSER (ASUSER_USERID,ASUSER_USERNAME,ASUSER_EMAIL,ASUSER_PWD) VALUES('ADMIN3','Administrator3','someone3@norming.com.cn','admin');
INSERT INTO ASUSER (ASUSER_USERID,ASUSER_USERNAME,ASUSER_EMAIL,ASUSER_PWD) VALUES('ADMIN4','Administrator4','someone4@norming.com.cn','admin');